# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact', models.IntegerField()),
                ('version', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('information', models.TextField()),
            ],
            options={
                'db_table': 'server',
            },
        ),
    ]
