# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('level', models.ForeignKey(db_column='level', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.RuleLevel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Rule', to_field='rule_id')),
            ],
            options={
                'db_table': 'signature',
            },
        ),
        migrations.CreateModel(
            name='SignatureCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.PositiveIntegerField()),
                ('cat_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'signature_category_mapping',
            },
        ),
    ]
