# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('rules', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(db_index=True)),
                ('src_ip', models.CharField(db_index=True, max_length=46, verbose_name='Source IP')),
                ('dst_ip', models.CharField(max_length=46, null=True, verbose_name='Destination IP')),
                ('src_port', models.PositiveIntegerField(null=True, verbose_name='Source Port')),
                ('dst_port', models.PositiveIntegerField(null=True, verbose_name='Destination Port')),
                ('alertid', models.CharField(db_index=True, default=None, max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('full_log', models.TextField()),
                ('is_hidden', models.PositiveSmallIntegerField(default=0)),
                ('tld', models.CharField(db_index=True, default='', max_length=5)),
                ('level', models.ForeignKey(db_column='level', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.RuleLevel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Rule', to_field='rule_id')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
