# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.PositiveIntegerField(default=0, unique=True)),
                ('maxsize', models.PositiveIntegerField(default=0)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('timeframe', models.PositiveIntegerField(default=0)),
                ('noalert', models.PositiveIntegerField(default=0)),
                ('ignore_attr', models.PositiveIntegerField(default=0)),
                ('overwrite', models.CharField(default='', max_length=10)),
                ('match', models.CharField(default='', max_length=300)),
                ('regex', models.CharField(default='', max_length=300)),
                ('ignore', models.CharField(default='', max_length=45)),
                ('decoded_as', models.CharField(default='', max_length=45)),
                ('category', models.CharField(default='', max_length=45)),
                ('srcip', models.CharField(default='', max_length=45)),
                ('dstip', models.CharField(default='', max_length=45)),
                ('extra_data', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=300)),
                ('program_name', models.CharField(default='', max_length=30)),
                ('hostname', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('weekday', models.CharField(default='', max_length=30)),
                ('regex_id', models.CharField(default='', max_length=300)),
                ('url', models.TextField(default='')),
                ('if_sid', models.CharField(default='', max_length=30)),
                ('if_group', models.CharField(default='', max_length=30)),
                ('if_level', models.PositiveIntegerField(default=0)),
                ('if_matched_sid', models.CharField(default='', max_length=30)),
                ('if_matched_group', models.CharField(default='', max_length=30)),
                ('same_id', models.CharField(default='', max_length=10)),
                ('same_source_ip', models.CharField(default='', max_length=10)),
                ('same_source_port', models.CharField(default='', max_length=10)),
                ('same_dst_port', models.CharField(default='', max_length=10)),
                ('same_location', models.CharField(default='', max_length=10)),
                ('same_user', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=200)),
                ('rule_list', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=300)),
                ('options', models.CharField(default='', max_length=200)),
                ('check_diff', models.CharField(default='', max_length=10)),
                ('group', models.CharField(default='', max_length=45)),
                ('action', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=100)),
                ('if_fts', models.CharField(default='', max_length=10)),
                ('check_if_ignored', models.CharField(default='', max_length=10)),
                ('compiled_rule', models.CharField(default='', max_length=30)),
                ('different_url', models.CharField(default='', max_length=10)),
                ('unknown', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='RuleLevel',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Rule level')),
                ('common_name', models.CharField(default='', max_length=100, verbose_name='Short name')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'db_table': 'rule_level',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='level',
            field=models.ForeignKey(db_column='level', on_delete=django.db.models.deletion.CASCADE, to='rules.RuleLevel'),
        ),
    ]
